# Generated by Django 5.2.4 on 2025-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
